Flower/Flower/Models/Stock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

//Модель Склада

namespace Flower.Models
{
    public class Stock
    {
        public Guid Id { get; set; }

        [Display(Name = "Название")]
        public string Name { get; set; }// Название склада
    }
}

Flower/Flower/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Flower.Models;

namespace Flower.Controllers
{
    public class StockController : Controller
    {
        // GET: Stock
        [Authorize]
        public ActionResult Index()
        {
            ApplicationDbContext dbContext = new ApplicationDbContext();

            var AllStocks = dbContext.Stocks.ToList();

            return View(AllStocks);
        }

        [Authorize]
        public ActionResult SelectStock(Guid Id)
        {
            ApplicationDbContext dbContext = new ApplicationDbContext();

            var SelectStock = dbContext.Stocks.FirstOrDefault(a => a.Id == Id);//Выбираем склад

            return View(SelectStock);
        }

        [Authorize]
        public ActionResult AddStock()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public RedirectResult AddNewStock(string Name)
        {
            ApplicationDbContext dbContext = new ApplicationDbContext();

            Stock st = new Stock {

                Id = Guid.NewGuid(),
                Name = Name
            };

            dbContext.Stocks.Add(st);
            dbContext.SaveChanges();

            return Redirect("~/Stock/Index");
        }

    }
}

Flower/Flower/Views/Stock/AddStock.cshtml
@model Flower.Models.Stock
@{
    ViewBag.Title = "Добавление склада";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("AddNewStock", "Stock", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.LabelFor(m => m.Name, new { @class = "control-label" })
    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
       <br />
    <input type="submit" class="btn btn-success" value="Добавить" />
}

Flower/Flower/Views/Stock/Index.cshtml
@model IEnumerable<Flower.Models.Stock>
@{
    ViewBag.Title = "Склады";
}

<h2>@ViewBag.Title</h2>

<a href="~/Stock/AddStock">Добавить новый склад</a>
<br /><br />

@foreach(var stock in Model)
{
    <a href="~/Stock/SelectStock/@stock.Id">@stock.Name</a><br />
}

Flower/Flower/Views/Stock/SelectStock.cshtml
@model Flower.Models.Stock
@{
    ViewBag.Title = "Склад";
}

<h2>@ViewBag.Title @Model.Name</h2>